apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-app-depl
  namespace: cvm-prod
spec: 
  replicas: 1 
  selector: 
    matchLabels:
        component: cms-app 
  template: 
    metadata:
      labels: 
        component: cms-app
    spec:
      containers: 
      - name: cms-app
        image: dmp-api-k8s-registry.com:443/dte-cms-app:V0.0.3 #abdm6464/dte-dnbo:V0.0.8
        imagePullPolicy: IfNotPresent 
        env:  
          - name: REDIS_HOST
            value: redis://redis-mq-event-bus:6379
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: sql_host
          - name: DB_USER
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: sql_host   
          - name: DB_PASS
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: sql_pass
          - name: DB_NAME
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: sql_name                     


       
