apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbss-depl
  namespace: cvm-prod
spec: 
  replicas: 1 
  selector: 
    matchLabels:
        component: dbss-api
  template: 
    metadata:
      labels: 
        component: dbss-api
    spec:
      containers: 
      - name: dbss-api 
        image: dmp-api-k8s-registry.com:443/dte-dbss-api #abdm6464/dte-dnbo:V0.0.8
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 3003 
        env:  
          - name : DBSS_API
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: dbss_api  
---                
        

apiVersion: v1
kind: Service
metadata: 
    name: dbss-api-svc
    namespace: cvm-prod
spec: 
  type: ClusterIP
  ports: 
    - port: 3003 
      targetPort: 3003 
  selector: 
    component: dbss-api