apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligible-app-depl
  namespace: cvm-prod
spec: 
  replicas: 1 
  selector: 
    matchLabels:
        component: eligible-app
  template: 
    metadata:
      labels: 
        component: eligible-app
    spec:
      containers: 
      - name: dbss-api 
        image: dmp-api-k8s-registry.com:443/dte-eligible-app:V0.0.1 #abdm6464/dte-dnbo:V0.0.8
        imagePullPolicy: IfNotPresent 
        env:  
          - name: REDIS_HOST
            value: redis://redis-event-bus:6379
        #   - name: DBSS_API
        #     value: http://dbss-svc:3000
       
