apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligible-api-depl
  namespace: cvm-prod
spec: 
  replicas: 1 
  selector: 
    matchLabels:
        component: eligible-api
  template: 
    metadata:
      labels: 
        component: eligible-api 
    spec:
      containers: 
      - name: eligible-api 
        image: dmp-api-k8s-registry.com:443/dte-eligible-api:0.0.3 #abdm6464/dte-dnbo:V0.0.8
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 3000 
        env:  
          - name: REDIS_HOST
            value: redis://redis-mq-event-bus:6379
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: pg_host
          - name: DB_USER
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: pg_user   
          - name: DB_PASS
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: pg_pass
          - name: DB_NAME
            valueFrom: 
              configMapKeyRef:
                name: partner-config
                key: pg_name            
---

apiVersion: v1
kind: Service
metadata: 
    name: eligible-api-svc
    namespace: cvm-prod
spec: 
  type: ClusterIP
  ports: 
    - port: 3001 
      targetPort: 3001 
  selector: 
    component: eligible-api