apiVersion: apps/v1
kind: Deployment
metadata:
  name: getway-api-depl
  namespace: cvm-prod
spec: 
  replicas: 1 
  selector: 
    matchLabels:
        component: getway-api
  template: 
    metadata:
      labels: 
        component: getway-api 
    spec:
      containers: 
      - name: getway-api 
        image: dmp-api-k8s-registry.com:443/dte-getway-api:0.0.1 #abdm6464/dte-dnbo:V0.0.8
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 3000 
        env:  
          - name: DBSS_API
            value: http://dbss-api-svc:3000
          - name: REDIS_HOST
            value: redis://redis-event-bus:6379
---

apiVersion: v1
kind: Service
metadata: 
    name: getway-api-svc
    namespace: cvm-prod
spec: 
  type: ClusterIP
  ports: 
    - port: 3000 
      targetPort: 3000 
  selector: 
    component: getway-api